config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  devise_for :users
  resources :users do 
  resources :skills do
  	member do
  		put "daps", to: "skills#upvote"
  	end
  resources :comments
  end
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	acts_as_votable
	#related to paperclip image
	has_attached_file :image, styles: { :medium => "300x300>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	validates_attachment_presence :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	acts_as_voter
	has_many :skills
	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#before_action :set_comment, only: [:create]

	def create
		@skill = Skill.find(params[:skill_id])
		@comment = @skill.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to :back
	end

private

	def set_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:skill_id, :body, :user_id)
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	before_action :set_user
	before_action :set_skill, only:[:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!

	def index
		@skills = @user.skills
	end

	def new
		@skill = current_user.skills.new
	end

	def create
		@skill = current_user.skills.new(skill_params)

		if @skill.save
			redirect_to user_skill_path(@user, @skill)
		else
			render 'new'
		end
	end

	def update
		if @skill.update(skill_params)
			redirect_to root_path
		end
	end

	def show
	end
	
	def edit
	end

	def destroy
		@skill.destroy
		redirect_to user_skills_path
	end

	def upvote
		if current_user.free_votes == 0
			flash[:error] = "Sorry, you're out of daps!"
			redirect_to :back
		elsif (current_user.voted_for? @skill)
			flash[:error] = "You've already given daps! Move on... "
			redirect_to :back
		else 
			@skill.liked_by current_user
			current_user.decrement!(:free_votes)
			redirect_to :back
		end
	end

	def downvote
		@skill.downvoted_by current_user
		redirect_to :back
	end

private

	def set_user
		@user = User.find(params[:user_id])
	end

	def set_skill
		@skill = @user.skills.find(params[:id])
	end

	def skill_params
		params.require(:skill).permit(:name, :description, :image)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@skills = @user.skills
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<%= simple_form_for @comment do |f| %>
	<%= f.input :body %>
	<%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class ="navbar navbar-default navbar-statictop">
	<div class="container">
	<div class="col-md-4">
	<div class="navbar-header">
		<%= link_to "What Skills!", root_path, data: { no_turbolink: true }, class:"navbar-brand" %>
	</div>
	</div>
	<div class="col-md-4 col-md-offset-4">
			<ul class="nav navbar-nav">
			<% if user_signed_in? %>
				<li class= "nav navbar-text"><%= "Available Votes: #{current_user.free_votes}" %></li>
				<li><%= link_to "New skill", new_user_skill_path(current_user) %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "New User", new_user_registration_path %></li>
				<li><%= link_to "Sign In", new_user_session_path %></li>
			<% end %>
			</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WhatSkills</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>


	<%= render 'layouts/header' %>
<div class="center">
	<strong>
    <% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
    <% end %>
	</strong>

</div>


</head>


<div class="container">
	<body>
		<%= yield %>
	</body>
</div>

</html>

app/views/skills/_form.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Skill</h1>
			</div>
			<div class="panel-body">
				<%= simple_form_for [@user, @skill],  html: {multipart: true}  do |f| %>
					<%= f.input :name %>
					<%= f.input :description %>
					<%= f.input :image %>
					<%= f.button :submit %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/skills/edit.html.erb
<%= render 'form' %>

app/views/skills/index.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
	<% if @skills.empty? %>
		<div class="center">
			<h3>*Chirp* *Chirp*</h3>
			<p>Nothing to see here... Add some skills to get started</p>
		</div>

	<% else %> 

	<%  @skills.each do |skill| %>
		<div class="box panel panel-default">
			<div class="image-container">
				<%= link_to (image_tag skill.image), user_skill_path(@user, skill)%>
			</div>
			</h1>
			<div class="panel-body">
				<h2><%= skill.name %> </h2>
				<p><%= skill.description %> <p>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<p class="center">
						<% if current_user.voted_for? skill %>
							<p>YOU'VE GIVEN DAPS!</p>
						<% else %> 
							<p>Show some love?</p>
						<% end %>
						</p>
					</div>
					<div class="col-md 6">
						<div class="btn-group pull-center">
							<%= link_to daps_user_skill_path(skill.user_id, skill), method: :put, class: "btn btn-default" do %>
								<span class="glyphicon glyphicon-heart"></span> 
								<%= skill.votes_for.size %>		
							<% end %>
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	<% end %>
	<% end %>
</div>

app/views/skills/new.html.erb
<%= render 'form' %>

app/views/skills/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="panel-default">
		<div class="panel-header">

		</div>
		<div class="panel-body">
			<div class="panel-image">
				<%= image_tag @skill.image.url(:medium) %>
			</div>
				<h1> <%= @skill.name %> </h1>
				<p> <%= @skill.description %> </p>	
			</div>
			<%= simple_form_for [@user, @skill, Comment.new] do |f| %>
				<%= f.input :body, label: "What do you really think?"%>
				<%= f.submit "Publish!", class: "btn btn-default" %>
			<% end %>
		<table class="table table-striped">
			<tbody>
				<br>
				<th>Comments:</th>
				<th>Says:</th>
				<% if @skill.comments.empty? %> 
					<tr>
						<td> Nothing to see over here... </td>
					</tr>
				<% end %>
				<% @skill.comments.each do |comment| %>
				<tr>
					<td>
						<%= comment.body %> 
					</td>
					<td>
						 <%= "#{comment.user.first_name} #{comment.user.last_name}" %>
					</td>
				</tr>
						
				<% end %>
			</tbody>

		</table>
		<% if @user == current_user %>
			<%= link_to "Edit", edit_user_skill_path(@user, @skill), class: "btn btn-default" %>
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<%= link_to "Delete", user_skill_path, data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
	
<% if !user_signed_in? %>
	<div class="jumbotron">
		<div class="row">
			<div class="center">
				<h1>What Skills?</h1>
				<p>... Be more like, "What skills!" Find what you need here! </p>
				<p><a class="btn btn-primary btn-lg" href="<%= new_user_registration_path %>" role="button">Sign up today!</a></p>
			</div>
		</div>
	</div>
<% end %>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Skill Count</th>
			<th>Link</th>
		</tr>
	</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= user.id %> </td>
					<td><%= user.first_name %> </td>
					<td><%= user.last_name %> </td>
					<td><%= user.email %></td>
					<td><%= user.skills.count %></td>
					<td><%= link_to "Profile", user_skills_path(user) %></td>
				</tr>
			<% end %>
		</tbody>
</table>

app/views/users/show.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
	<% @skills.each do |skill| %>
		<div class="box panel panel-default">
			<div class="image-container">
				<%= link_to (image_tag skill.image), skill %>
			</div>
			</h1>
			<div class="panel-body">
				<h2><%= skill.name %> </h2>
				<p><%= skill.description %> <p>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<p>Have you liked this?: <%= skill.liked_by current_user %></p>
					</div>
					<div class="col-md 6">
						<div class="btn-group pull-center">
							<%= link_to daps_skill_path(skill), method: :put, class: "btn btn-default" do %>
								<span class="glyphicon glyphicon-heart"></span> 
								<%= skill.votes_for.size %>		
							<% end %>
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	<% end %>
</div>